segments: Add missing API for "dot" control on big 7-segments
adafruit/Adafruit_CircuitPython_HT16K33 pull request #41
Opened 2019-10-21 10:19 UTC by vdehors

There are 4 side LEDs around the 4 7-segments on 1.2" packages of HT16k33
(https://www.adafruit.com/product/1270). This commit adds an API to control
them (set and get).

There already was setter and getter to control "ampm" dot (the one at the
top-right). This API is still working but now use the new added functions.

2019-10-21 20:20 UTC, tannewt requested changes
Thank you for this change!

In general we avoid get/set methods because they can be implemented with properties (like `ampm`) or data descriptors like `colon`. ampm and colon already cover two of the four cases you are adding support here.

I'd recommend adding two more properties for top_left_dot and bottom_left_dot that are implemented like ampm. You can use your new get/set methods internally by adding an _ to the start of the name. The other way do do it is by using [a data descriptor](https://docs.python.org/3/howto/descriptor.html) class for all three.

2019-10-22 14:23 UTC, vdehors commented
Hi tannewt,

Indeed, I didn't see the Colon class (which implemented what I needed btw). I made your changes but the "colon" property may be enough (with doc) ?

2019-11-02 00:08 UTC, tannewt requested changes
One comment about two_dots_center. Good otherwise. Thanks!

2019-11-02 00:08 UTC, tannewt commented on adafruit_ht16k33/segments.py
> +    def two_dots_center(self):
Isn't this the colon? There shouldn't be two ways to set it.

2019-11-17 02:28 UTC, bobdog6861 commented
I would like to disable the zero blanking of first and second digits, so that I can display the zeros.  I cannot seem to figure out where in the driver it is making that decision.   Is it in _put, in ht16k33.py  ?

2019-11-19 19:49 UTC, tannewt commented
@bobdog6861 unless you are testing with this version, please open a separate issue for your question.

2019-12-31 20:53 UTC, makermelissa commented
I'm thinking this PR may not be necessary. I'm going to attempt to set up a small code example to light up all segments and dots and will paste it here if I can get it working.

2019-12-31 21:22 UTC, makermelissa commented
Ok, here's how you fill each thing with the way the library currently is now:
```
import board
from adafruit_ht16k33 import segments
i2c = board.I2C()
display = segments.BigSeg7x4(i2c)

# Clear the display.
display.fill(0)

# Fill Everything
display.print("8888") # Each Digit. You can also use display[0]
display.colon[0] = True  # Middle Colon
display.colon[1] = True  # Left Colon
display.ampm = True  # Upper Dot
```

2019-12-31 21:35 UTC, makermelissa commented
@vdehors, I am going to reopen this. I now understand this adds the ability to add separate control of the left side dots, which is excellent. However, as @tannewt suggested, we probably should remove the two_dots_center setter and getters because of the redundancy.

2020-01-08 19:02 UTC, kattni commented
@makermelissa Thank you for reviewing this PR! Please consider making the necessary changes yourself so we can get this merged. If you need assistance with that, let me know. Thanks!

2020-01-14 21:57 UTC, makermelissa approved these changes
Looks good. Thank you!

2020-01-14 21:57 UTC, merged