Adding new animation demo to show what can be done when using set_dig…
adafruit/Adafruit_CircuitPython_HT16K33 pull request #59
Opened 2020-02-11 02:16 UTC by geekguy-wy

This adds a new animation demo that shows a little bit of what can be done when using set_digit_raw()

2020-02-11 02:24 UTC, ladyada commented
hiya please lint and then retag us to review

2020-02-11 03:12 UTC, geekguy-wy commented
Done and ready for review.

2020-02-11 17:00 UTC, makermelissa requested changes
Looks like there are a few places with commented out code. Otherwise it looks good.

2020-02-11 17:00 UTC, makermelissa commented on examples/ht16k33_animation_demo.py
> +    # cy in range(cycles):
Could you either make this comment a little more clear or if it's commented out code, please remove. Thanks

2020-02-11 17:00 UTC, makermelissa commented on examples/ht16k33_animation_demo.py
> +        #animate([0], [M, H, 0x0], delay)
Is there a reason this is commented out?

2020-02-11 17:00 UTC, makermelissa commented on examples/ht16k33_animation_demo.py
> +    #for cy in range(cycles):
Let's remove any commented out code that is not intended to be used.

2020-02-13 08:34 UTC, geekguy-wy commented on examples/ht16k33_animation_demo.py
> +    # cy in range(cycles):
I removed some commented out code and comments that were not needed.

2020-02-13 08:35 UTC, geekguy-wy commented on examples/ht16k33_animation_demo.py
> +        #animate([0], [M, H, 0x0], delay)
It was an alternate ending to the animation I thought I might use. Removed.

2020-02-13 08:36 UTC, geekguy-wy commented on examples/ht16k33_animation_demo.py
> +    #for cy in range(cycles):
Done. I have a new version that has some more complex animations.

2020-02-13 16:39 UTC, makermelissa commented
If PR #60 supersedes this PR, then please close. They both have the animation demo. Thanks.

2020-02-13 19:21 UTC, geekguy-wy commented
This PR is superseded by PR #60.

2020-02-13 19:21 UTC, closed without merging