Add typing
adafruit/Adafruit_CircuitPython_HT16K33 pull request #92
Opened 2021-10-25 02:01 UTC by tekktrik

I believe I typed this correctly.  Was a little unsure of using the CircuitPython "_typing" library.

2021-10-26 02:14 UTC, tekktrik commented
Addressed issues from pre-commit check

2021-10-27 22:46 UTC, gamblor21 requested changes
Good work. I didn't test it on actual hardware and noted a couple things I saw.

2021-10-27 22:46 UTC, gamblor21 commented on adafruit_ht16k33/ht16k33.py
> +    from typing import Optional
You will have to also import ReadableBuffer

2021-10-27 22:46 UTC, gamblor21 commented on adafruit_ht16k33/ht16k33.py
> +    def _write_cmd(self, byte: "_typing.ReadableBuffer"):
I believe this can just be `byte: ReadableBuffer` once it is imported.

2021-10-27 22:46 UTC, gamblor21 commented on adafruit_ht16k33/matrix.py
> +    def image(self, img: "PIL.Image"):
I think this has to be imported in the try at the top.

2021-10-28 01:23 UTC, FoamyGuy commented on adafruit_ht16k33/matrix.py
> +    def image(self, img: "PIL.Image"):
Lets import it like this:
```
from PIL import Image
```
and then in the `img: Image` 

This seems to get the IDE able to follow through to the right class which didn't work for me with `import PIL.Image`

2021-10-28 02:11 UTC, tekktrik commented
Thanks @gamblor21 and @FoamyGuy for the helpful feedback!  Appreciate the help for a new contributor.  Just resubmitted with changes per review comments.

2021-10-28 02:15 UTC, tekktrik commented
It actually just kicked back on building the docs, was it because it failed importing '_typing' so it never imported I2C?

2021-10-28 13:35 UTC, tekktrik commented
Actually, rereading the documentation, is '_typing' actually a real library. or should I create a Union named ReadableBuffer within the import instead?

2021-10-28 13:44 UTC, FoamyGuy commented
> Actually, rereading the documentation, is '_typing' actually a real library. or should I create a Union named ReadableBuffer within the import instead?

Im not familiar with  `_typing` not sure if it's a real module or not, but I don't think it's one that we've used for any of these so far.

I'm not certain where the ReadableBuffer import should come from though.

I'll take a look into this one and see if I can figure out the right way to import it to make the sphinx build happier. But it's likely I won't be able to get to it until tomorrow evening.

2021-10-28 14:10 UTC, tekktrik commented
Much appreciated!  Let me know when you determine how to do it!

2021-10-30 21:33 UTC, FoamyGuy commented on adafruit_ht16k33/ht16k33.py
> +    def _write_cmd(self, byte: ReadableBuffer):
I think we can use `bytearray` for the type here. That is what's listed in the docs for `I2CDevice.write()` Which is what this value gets passed to. https://circuitpython.readthedocs.io/projects/busdevice/en/latest/api.html#adafruit_bus_device.i2c_device.I2CDevice.write

2021-10-30 21:54 UTC, tekktrik commented
Awesome, changes made!

2021-10-30 22:00 UTC, FoamyGuy commented
Try adding `pillow` to the requirements.txt file. I think that should make sphinx recognize the Image object.

2021-10-30 22:09 UTC, tekktrik commented
Awesome, thanks for all the help

2021-10-30 22:16 UTC, FoamyGuy commented
It wants an extra empty line at the end of requirements.txt as well. (picky CI). Thanks for working through the issues.

2021-10-30 22:19 UTC, tekktrik commented
Haha no worries, thanks for all the help!

2021-10-30 23:19 UTC, FoamyGuy approved these changes
Looks good to me. Thank you @tekktrik

2021-10-30 23:20 UTC, merged